version: '3.8'

services:
  backend:
    build: ./backend
    container_name: semantic-backend
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,https://search-poc.anuragkurmi.dev
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://ai-search.anuragkurmi.dev
    container_name: semantic-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
